[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir ../.."

[build.environment]
HUGO_VERSION = "0.78.2"
HUGO_THEME = "repo"
HUGO_BASEURL = "https://ublogger.netlify.app"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/es/404.html"
  status = 404

[[redirects]]
  from = "/es/*"
  to = "/es/404.html"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404