[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "10.8.2"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[[redirects]]
  from = "/:splat.md"
  to = "/:splat/index.md"
  status = 200

[[redirects]]
  from = "/*"
  to = "/es/404.html"
  status = 404

[[redirects]]
  from = "/es/*"
  to = "/es/404.html"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404