name: Run Maestro Web Tests

on:
  workflow_dispatch:

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  maestro-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run Maestro Web Tests
        run: |
          export PATH="$HOME/.maestro/bin:$PATH"
          export MAESTRO_DRIVER_STARTUP_TIMEOUT=120000
          mkdir -p $HOME/.maestro-chrome-data
          maestro test .maestro/ --format junit --output report.xml
        env:
          CHROME_USER_DATA_DIR: ${{ runner.temp }}/chrome-user-data

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-test-report
          path: |
            report.xml
            ~/.maestro/tests/**/*
          if-no-files-found: warn
