name: Run Maestro Web Tests

on:
  workflow_dispatch:

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  maestro-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
          install-dependencies: true

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Setup Xvfb for headless Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 2

      - name: Run Maestro Web Tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 2
          retry_on: error
          command: |
            export PATH="$HOME/.maestro/bin:$PATH"
            maestro test .maestro/ --format junit --output report.xml
        env:
          MAESTRO_CLI_NO_ANALYTICS: "1"
          DISPLAY: ":99"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-test-report
          path: |
            report.xml
            ~/.maestro/tests/**/*
          if-no-files-found: warn
